name : Run CI Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run_ci_tests:
    name: Run CI Tests
    runs-on: self-hosted
    steps:
    - name: Run CI Tests
      run: 
        python ${{runner.workspace}}\grpc-labview\tests\run_tests.py
