name: Build Release artifacts

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_release_artifacts:
    name: draft release 
    runs-on: self-hosted
    steps:
    
    - name: Zip Release Artifacts
      run: |
        cd ${{runner.workspace}}/grpc-labview/labview source/Builds
        tar -cavf grpc-labview.zip *.vip

    - if: startsWith(github.ref, 'refs/tags/v')
      name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Verison ${{ github.ref }}
        draft: true

    - if: startsWith(github.ref, 'refs/tags/v')
      name: Upload Release Artifacts to Draft Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{runner.workspace}}\grpc-labview\labview source\Builds\grpc-labview.zip
          asset_name: grpc-labview.zip
          asset_content_type: application/zip