name: Trigger AzDO CIs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  trigger_azdo_ci:
    name: Trigger Main CI
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v3
      with:
        path: ${RUNNER_TEMP}/grpc-labview-artifacts

    - name: Stage Artifacts
      run: python ${{runner.workspace}}/grpc-labview/grpc-labview/build-it/stage_artifacts.py
      --downloaded_path "${RUNNER_TEMP}/grpc-labview-artifacts"
      --staging_path "${RUNNER_TEMP}/grpc-labview-staged-artifacts"
    
    - name: Build VI Packages
      run:  python ${{runner.workspace}}/grpc-labview/grpc-labview/build-it/build.py
      --target All
      --pathToBinaries "${RUNNER_TEMP}/grpc-labview-staged-artifacts"
