name: Trigger AzDO CIs

on:
  workflow_call:
  workflow_dispatch:

jobs:
  trigger_azdo_ci:
    name: Trigger Main CI
    runs-on: self-hosted
    jobs:
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R
    
    # - stage: Build Vipkgs
    #   displayName: Run Python script
    #   job:
    #     run  python ${{runner.workspace}}/grpc-labview/grpc-labview/build-it/build.py
    #   --target All
    #   --pathToBinaries "${{runner.workspace}}/grpc-labview/grpc-labview-artifacts/TopLevelDlls"
